#!/bin/bash

set -e
set -u

prefix=__
delim=.
pgpass=${PGPASSFILE:-${HOME}/.pgpass}

prog=$(basename "$0")
dir=$(dirname "$0")
name=${prog#${prefix}}

rm -f -v "$dir"/"$name$delim"*

cat -- "$pgpass" | while IFS=: read -r dbhost dbport dbname dbuser dbpass ; do
  if [ "$dbname" = "$dbuser" ] ; then
    shorthand=${dbname}
  elif ! [ "${dbuser#${dbname}}" = "$dbuser" ] ; then
    shorthand=${dbuser}
  else
    shorthand=${dbname}${delim}${dbuser}
  fi
  script=${dir}/${name}${delim}${shorthand}

  if [ -f "$script" ] ; then
    echo >&2 "ERROR: conflicting entry: $script"
  else

    cat >"$script" <<EOF
#!/bin/bash

export PGHOST=\${PGHOST:-$dbhost}
export PGPORT=\${PGPORT:-$dbport}
export PGDATABASE=\${PGDATABASE:-$dbname}
export PGUSER=\${PGUSER:-$dbuser}
export PGPASSFILE=\${PGPASSFILE:-$pgpass}
export DBI_DRIVER=\${DBI_DRIVER:-Pg}

exec -- "\${@-psql}"
EOF

    chmod +x "$script"
    echo "  $script"
  fi
done
